#!/usr/bin/env bash
# ==============================================================================
# AR Radius - One-Command Installer for Ubuntu 24.04
# ==============================================================================
# Usage:
#   curl -sSL https://raw.githubusercontent.com/marsh4200/ar-radius/main/install.sh | sudo bash
# ==============================================================================

set -euo pipefail

# ---------- Configuration ----------------------------------------------------
REPO_URL="https://github.com/marsh4200/ar-radius.git"
REPO_BRANCH="main"
INSTALL_DIR="/opt/ar-radius"
WEB_DIR="${INSTALL_DIR}/web"
WEB_PORT="9916"

DB_NAME="radius"
DB_USER="radius"
DB_HOST="127.0.0.1"

# Colours / logging
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log()  { echo -e "${BLUE}[AR-RADIUS]${NC} $*"; }
ok()   { echo -e "${GREEN}[ OK ]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[FAIL]${NC} $*" >&2; }

# ---------- Pre-flight checks -----------------------------------------------
if [[ $EUID -ne 0 ]]; then
    err "This installer must be run as root (use sudo)."
    exit 1
fi

if ! grep -qi "ubuntu" /etc/os-release; then
    warn "This installer is designed for Ubuntu 24.04. Proceeding anyway..."
fi

UBUNTU_VER=$(lsb_release -rs 2>/dev/null || echo "unknown")
log "Detected Ubuntu version: ${UBUNTU_VER}"

# Generate strong random passwords
DB_PASS=$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)
ADMIN_PASS=$(openssl rand -base64 12 | tr -d '/+=' | cut -c1-16)

log "Starting AR Radius installation..."

# ---------- 1. System update + dependencies ---------------------------------
log "Updating apt cache and installing prerequisites..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
    curl wget git unzip ufw openssl \
    software-properties-common ca-certificates \
    apache2 libapache2-mod-php \
    php php-cli php-mysql php-curl php-json php-mbstring php-xml php-gd php-zip \
    mariadb-server mariadb-client \
    freeradius freeradius-mysql freeradius-utils
ok "Base packages installed."

# ---------- 2. MariaDB setup ------------------------------------------------
log "Configuring MariaDB..."
systemctl enable --now mariadb >/dev/null 2>&1 || true

# Secure & create database
mysql --protocol=socket -uroot <<SQL
CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL
ok "Database '${DB_NAME}' and user '${DB_USER}' created."

# ---------- 3. Clone repository ---------------------------------------------
log "Fetching AR Radius from GitHub..."
if [[ -d "${INSTALL_DIR}/.git" ]]; then
    log "Existing installation found - updating..."
    cd "${INSTALL_DIR}"
    git fetch --all -q
    git reset --hard "origin/${REPO_BRANCH}" -q
else
    rm -rf "${INSTALL_DIR}"
    git clone -q -b "${REPO_BRANCH}" "${REPO_URL}" "${INSTALL_DIR}"
fi
ok "Repository synced to ${INSTALL_DIR}"

# ---------- 4. Import database schema ---------------------------------------
log "Importing database schema..."
mysql -u"${DB_USER}" -p"${DB_PASS}" "${DB_NAME}" < "${INSTALL_DIR}/sql/schema.sql"
ok "Schema imported."

# ---------- 5. Create admin user --------------------------------------------
ADMIN_USER="admin"
ADMIN_HASH=$(php -r "echo password_hash('${ADMIN_PASS}', PASSWORD_BCRYPT);")
mysql -u"${DB_USER}" -p"${DB_PASS}" "${DB_NAME}" <<SQL
INSERT INTO ar_admins (username, password_hash, created_at)
VALUES ('${ADMIN_USER}', '${ADMIN_HASH}', NOW())
ON DUPLICATE KEY UPDATE password_hash=VALUES(password_hash);
SQL
ok "Admin user created."

# ---------- 6. Write web configuration --------------------------------------
log "Writing web app configuration..."
mkdir -p "${WEB_DIR}/includes"
cat > "${WEB_DIR}/includes/config.php" <<PHP
<?php
// Auto-generated by installer - DO NOT EDIT MANUALLY
return [
    'db' => [
        'host'    => '${DB_HOST}',
        'name'    => '${DB_NAME}',
        'user'    => '${DB_USER}',
        'pass'    => '${DB_PASS}',
        'charset' => 'utf8mb4',
    ],
    'app' => [
        'name'    => 'AR Radius',
        'port'    => ${WEB_PORT},
        'install_dir' => '${INSTALL_DIR}',
        'repo'    => '${REPO_URL}',
        'branch'  => '${REPO_BRANCH}',
    ],
    'session' => [
        'name'     => 'ar_radius_sess',
        'lifetime' => 3600,
    ],
];
PHP
chmod 640 "${WEB_DIR}/includes/config.php"
ok "Web configuration written."

# Write version file
if [[ ! -f "${INSTALL_DIR}/VERSION" ]]; then
    echo "1.0.0" > "${INSTALL_DIR}/VERSION"
fi

# ---------- 7. FreeRADIUS SQL module ----------------------------------------
log "Configuring FreeRADIUS SQL module..."
RAD_DIR="/etc/freeradius/3.0"
[[ -d "$RAD_DIR" ]] || RAD_DIR="/etc/raddb"   # fallback

# Import default FreeRADIUS schema (creates radcheck/radacct/etc)
if [[ -f "/etc/freeradius/3.0/mods-config/sql/main/mysql/schema.sql" ]]; then
    mysql -u"${DB_USER}" -p"${DB_PASS}" "${DB_NAME}" \
        < /etc/freeradius/3.0/mods-config/sql/main/mysql/schema.sql 2>/dev/null || true
fi

# Configure SQL module
cp "${INSTALL_DIR}/config/freeradius-sql" "${RAD_DIR}/mods-available/sql"
sed -i "s|@@DB_HOST@@|${DB_HOST}|g; s|@@DB_NAME@@|${DB_NAME}|g; s|@@DB_USER@@|${DB_USER}|g; s|@@DB_PASS@@|${DB_PASS}|g" "${RAD_DIR}/mods-available/sql"
ln -sf "${RAD_DIR}/mods-available/sql" "${RAD_DIR}/mods-enabled/sql"
chgrp -h freerad "${RAD_DIR}/mods-available/sql" "${RAD_DIR}/mods-enabled/sql" 2>/dev/null || true
chmod 640 "${RAD_DIR}/mods-available/sql"

# Enable SQL in default sites
for site in default inner-tunnel; do
    SITE_FILE="${RAD_DIR}/sites-enabled/${site}"
    if [[ -f "$SITE_FILE" ]]; then
        # Uncomment "sql" lines in authorize{}, accounting{}, session{}, post-auth{}
        sed -i 's|^[[:space:]]*#[[:space:]]*sql$|\tsql|g' "$SITE_FILE" || true
    fi
done
ok "FreeRADIUS SQL module configured."

# ---------- 8. Apache vhost on port 9916 ------------------------------------
log "Configuring Apache vhost on port ${WEB_PORT}..."

# Add Listen directive
if ! grep -q "^Listen ${WEB_PORT}$" /etc/apache2/ports.conf; then
    echo "Listen ${WEB_PORT}" >> /etc/apache2/ports.conf
fi

cp "${INSTALL_DIR}/config/apache-vhost.conf" /etc/apache2/sites-available/ar-radius.conf
sed -i "s|@@WEB_DIR@@|${WEB_DIR}|g; s|@@WEB_PORT@@|${WEB_PORT}|g" /etc/apache2/sites-available/ar-radius.conf

a2enmod rewrite headers >/dev/null 2>&1 || true
a2dissite 000-default.conf >/dev/null 2>&1 || true
a2ensite ar-radius.conf >/dev/null 2>&1 || true
ok "Apache vhost configured."

# ---------- 9. Permissions --------------------------------------------------
log "Setting permissions..."
chown -R www-data:www-data "${WEB_DIR}"
find "${WEB_DIR}" -type d -exec chmod 755 {} \;
find "${WEB_DIR}" -type f -exec chmod 644 {} \;
chmod 640 "${WEB_DIR}/includes/config.php"
chown root:www-data "${WEB_DIR}/includes/config.php"

# Allow www-data to run update.sh & disconnect commands via sudo
cat > /etc/sudoers.d/ar-radius <<'SUDO'
www-data ALL=(root) NOPASSWD: /opt/ar-radius/update.sh
www-data ALL=(root) NOPASSWD: /usr/bin/systemctl restart apache2
www-data ALL=(root) NOPASSWD: /usr/bin/systemctl restart freeradius
SUDO
chmod 440 /etc/sudoers.d/ar-radius

chmod +x "${INSTALL_DIR}/update.sh" "${INSTALL_DIR}/install.sh"
ok "Permissions set."

# ---------- 10. Firewall ----------------------------------------------------
log "Configuring firewall..."
if command -v ufw >/dev/null 2>&1; then
    ufw allow 22/tcp        >/dev/null 2>&1 || true
    ufw allow ${WEB_PORT}/tcp >/dev/null 2>&1 || true
    ufw allow 1812/udp      >/dev/null 2>&1 || true   # RADIUS auth
    ufw allow 1813/udp      >/dev/null 2>&1 || true   # RADIUS acct
    yes | ufw enable        >/dev/null 2>&1 || true
    ok "UFW rules applied."
else
    warn "ufw not available - skipping firewall config."
fi

# ---------- 11. Enable + start services -------------------------------------
log "Enabling and starting services..."
systemctl daemon-reload
systemctl enable apache2 mariadb freeradius >/dev/null 2>&1 || true
systemctl restart apache2
systemctl restart mariadb
systemctl restart freeradius || warn "FreeRADIUS failed to start - check 'freeradius -X' for debugging"
ok "Services started."

# ---------- 12. Save credentials --------------------------------------------
CREDS_FILE="/root/ar-radius-credentials.txt"
cat > "${CREDS_FILE}" <<EOF
================================================================
 AR Radius - Installation Credentials
================================================================
Installed on : $(date)

Web GUI URL  : http://$(hostname -I | awk '{print $1}'):${WEB_PORT}/
Admin login  : ${ADMIN_USER}
Admin pass   : ${ADMIN_PASS}

Database     : ${DB_NAME}
DB User      : ${DB_USER}
DB Pass      : ${DB_PASS}

Install dir  : ${INSTALL_DIR}
================================================================
KEEP THIS FILE SAFE - it contains your credentials.
================================================================
EOF
chmod 600 "${CREDS_FILE}"

# ---------- Done ------------------------------------------------------------
IP_ADDR=$(hostname -I | awk '{print $1}')
echo
echo -e "${GREEN}=========================================================${NC}"
echo -e "${GREEN}  AR Radius installation complete!${NC}"
echo -e "${GREEN}=========================================================${NC}"
echo
echo -e "  Web GUI : ${BLUE}http://${IP_ADDR}:${WEB_PORT}/${NC}"
echo -e "  Login   : ${BLUE}${ADMIN_USER}${NC}"
echo -e "  Pass    : ${BLUE}${ADMIN_PASS}${NC}"
echo
echo -e "  Credentials saved to: ${YELLOW}${CREDS_FILE}${NC}"
echo
echo -e "${GREEN}=========================================================${NC}"
